name: Render README

on:
  push:
    paths:
      - README.Rmd
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up R
      - uses: r-lib/actions/setup-r@v2

      # Step 3: Set up Pandoc (necessary for rendering R Markdown)
      - uses: r-lib/actions/setup-pandoc@v2

      # Step 4: Install the required R packages (e.g., rmarkdown)
      - name: Install rmarkdown
        run: |
          install.packages("rmarkdown", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      # Step 5: Render README from Rmd to MD
      - name: Render README
        run: |
          rmarkdown::render("README.Rmd", output_format = "github_document")
        shell: Rscript {0}

      # Step 6: Commit and push the newly rendered README.md
      - name: Commit README.md
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Re-render README.md" || echo "No changes"
          git push
